export const PROFILE = {
  name: "Venu Gopal Erra",
  pronouns: "He/Him",
  title: "Project Manager, PMP®, PRINCE2® Practitioner, CSM®",
  currentRole: "Senior Project Leader",
  company: "ALTEN LTD - UK",
  location: "Derby, England, United Kingdom",
  linkedin: "https://www.linkedin.com/in/venu-gopal-erra-73919451/",
  connections: "500+",
  yearsExperience: "18+",
  domains: ["Rail Transport", "Automotive"],
  openToWork: true,
  targetRoles: [
    "Project Manager",
    "Project Manager Program Management Office",
    "Project Manager Scrum Master",
    "Senior Project Leader",
    "Senior Test Engineer",
  ],
  about: [
    "With over 18 years of experience, I specialize in project management within the rail transport and automotive domains. As a Senior Project Manager at ALTEN LTD - UK, I lead projects to successful completion by ensuring timely delivery, budget adherence, and quality outcomes. My role involves creating cost models, monitoring performance metrics, and managing risks to achieve high-impact results.",
    "By leveraging certifications like PMP®, PRINCE2® Practitioner, and CSM®, I collaborate with teams to foster efficient project execution and client satisfaction. I am committed to enabling organizational success through proactive actions, productivity improvements, and seamless client communication.",
  ],
  experience: [
    {
      title: "Senior Project Leader",
      company: "ALTEN LTD - UK",
      type: "Full-time",
      period: "Jun 2023 – Present",
      duration: "2 yrs 10 mos",
      location: "London, England, United Kingdom · Hybrid",
      skills: ["Project Management", "Rail Transport"],
      highlights: [
        "Delivering various types of projects on time, within budget, and meeting quality expectations",
        "Contributing to creating cost models and technical offers for new bids",
        "Monitoring team and project performance, setting key performance indicators",
        "Identifying and managing project risks and opportunities",
        "Preparing and leading regular client meetings, monthly reporting",
        "Tracking and analyzing project financial performance",
        "Maintaining clear focus on project scope and requirements",
        "Deploying organisational tools, processes for quality and maturity in projects",
      ],
      teamManagement: [
        "Forecasting and coordinating workload, ensuring correct team sizing",
        "Defining future team makeup, working with Business Team and Recruiters",
        "Integrating new team members and managing skills and capability",
        "Leading teams by example, upholding high standards for quality, health, safety, and environment",
      ],
    },
    {
      title: "Project Manager",
      company: "Alten UK Ltd",
      subtitle: "Rail and Automotive",
      period: "Jun 2023 – Present",
      duration: "2 yrs 10 mos",
      highlights: [
        "Lead delivery of diverse rail and automotive projects",
        "Ensuring alignment with client expectations, regulatory standards, and internal quality benchmarks",
        "Coordinate production releases across multidisciplinary teams",
      ],
    },
    {
      title: "Project Manager",
      company: "Schneider Electric (Cognizant)",
      type: "Full-time",
      period: "Jan 2022 – Jun 2023",
      duration: "1 yr 6 mos",
      location: "Hyderabad, Telangana, India",
      highlights: [],
    },
    {
      title: "Project Leader and Scrum Master",
      company: "Cyient",
      type: "Full-time",
      period: "Sep 2020 – Feb 2022",
      duration: "1 yr 6 mos",
      location: "Hyderabad",
      highlights: [],
    },
    {
      title: "Team Lead",
      company: "Cyient",
      period: "Jul 2014 – Sep 2020",
      duration: "6 yrs 3 mos",
      highlights: [],
    },
    {
      title: "Scrum Master",
      company: "Bombardier Transportation (Cyient RCS)",
      period: "Dec 2018 – Dec 2021",
      duration: "3 yrs 1 mo",
      highlights: [
        "Facilitated Agile ceremonies including Product increment Planning, daily stand-ups, retrospectives, and SOS sessions",
        "Estimated work effort and distributed tasks based on team strengths",
      ],
    },
  ],
  education: [
    {
      institution: "VNR Vignana Jyothi Institute of Engineering and Technology (VNRVJIET)",
      degree: "Bachelor of Technology - BTech",
      field: "Electrical, Electronics and Communications Engineering",
      period: "2003 – 2007",
    },
    {
      institution: "Kendriya Vidyalaya",
      period: "1991 – 2000",
    },
  ],
  certifications: ["PMP®", "PRINCE2® Practitioner", "CSM®"],
  skills: [
    "Project Management",
    "Rail Transport",
    "Automotive",
    "Agile / Scrum",
    "PRINCE2",
    "PMP",
    "Risk Management",
    "Stakeholder Management",
    "Budget Management",
    "Team Leadership",
    "Cost Modelling",
    "Performance Metrics",
    "Quality Assurance",
    "Visual SourceSafe (VSS)",
  ],
  jobSearchLocations: ["UK", "Hyderabad", "Telangana", "India", "Remote"],
};
